language: dart

sudo: required
addons:
  chrome: stable

jobs:
  include:
    - stage: beta
      script: dart ./tool/travis.dart
      dart: beta

stages:
  # - stable
  - beta
  # - dev

# Only building master means that we don't run two builds for each pull request.
# branches:
#  only:
#    - master
#    - dart2

cache:
  directories:
    - $HOME/.pub-cache