name: tekartik_js_utils
version: 0.1.1
description: Bug investigation
author: Alexandre Roux <alex@tekartik.com>
homepage: https://github.com/tekartik/js_utils.dart
deploy_to: none
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  js: any

dev_dependencies:
  process_run: '>=0.10.0+1'
  test: '>=1.2.0'
  build_runner: '>=1.7.0'
  build_test: '>=0.10.8'
  build_web_compilers: '>=1.2.2'

dependency_overrides:
